#cloudinary 
---
development:
  cloud_name: necthub
  api_key: '578614768239533'
  api_secret: DE2faPAe8KpFWFWtcy_bDJJ1TSE
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: necthub
  api_key: '578614768239533'
  api_secret: DE2faPAe8KpFWFWtcy_bDJJ1TSE
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: necthub
  api_key: '578614768239533'
  api_secret: DE2faPAe8KpFWFWtcy_bDJJ1TSE
  enhance_image_tag: true
  static_image_support: false